## 1. Import and inspect data

In [56]:
import pandas as pd

# create a dataframe
df = pd.read_json("../data/raw/ll84_raw.json", orient="records")

print("A look at the raw data...")
df.head()
df.info()
df.describe()

A look at the raw data...
<class 'pandas.DataFrame'>
RangeIndex: 33684 entries, 0 to 33683
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   nyc_borough_block_and_lot  33684 non-null  str
 1   site_eui_kbtu_ft           33684 non-null  str
dtypes: str(2)
memory usage: 526.4 KB

       nyc_borough_block_and_lot site_eui_kbtu_ft
count                      33684            33684
unique                     29063             2705
top                Not Available    Not Available
freq                         436             2796

## 2. Rename columns

In [58]:
# standardize column names
df.columns = df.columns.str.strip().str.lower()

df = df.rename(columns={
    "nyc_borough_block_and_lot": "bbl",
    "site_eui_kbtu_ft": "eui"
})

print("Inspect row names")
df.head()
df.info()

Inspect row names
<class 'pandas.DataFrame'>
RangeIndex: 33684 entries, 0 to 33683
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   bbl     33684 non-null  str
 1   eui     33684 non-null  str
dtypes: str(2)
memory usage: 526.4 KB

## 3. Set Data Types

In [59]:
# convert eui from str to numerical
df["eui"] = pd.to_numeric(df["eui"], errors="coerce")

print("Inspect new typing: ")
print(df.dtypes)

Inspect new typing:
bbl        str
eui    float64
dtype: object

## 4. Standardize data entries

In [ ]:
print("test for null and duplicate rows pre-cleaning: ")
print("Null counts: ")
print(df.isnull().sum())
print(f'Starting duplicate rows: {df.duplicated().sum()}')
print(f"Starting N/A bbl rows: {(df['bbl'] == 'Not Available').sum()}")

# drop duplicate rows
df.drop_duplicates(inplace=True)

# drop entries with critical missing values
df.dropna(subset=['eui'], inplace=True) # drop if there is no eui
df = df[df['bbl'] != "Not Available"] # drop any row with out bbl

print("test for null and duplicate rows post-cleaning: ")
print("Null counts: ")
print(df.isnull().sum())
print(f'Remaining duplicate rows: {df.duplicated().sum()}')
print(f"Remaining N/A bbl rows: {(df['bbl'] == 'Not Available').sum()}")

test for null and duplicate rows pre-cleaning:
Null counts:
bbl       0
eui    2796
dtype: int64
Starting duplicate rows: 1901
Starting N/A bbl rows: 436
test for null and duplicate rows post-cleaning:
bbl    0
eui    0
dtype: int64
Remaining N/A bbl rows: 0
Remaining duplicate rows: 0

## Final check

In [61]:
print(df.shape)
print(df.isnull().sum())
print(df.dtypes)
df.head(10)

(30135, 2)
bbl    0
eui    0
dtype: int64
bbl        str
eui    float64
dtype: object

          bbl    eui
0  3052370038   83.8
1  1008190014   77.8
2  1010557501   69.7
3  1004750056   78.1
4  1006980044   24.0
5  4019860001   11.4
6  1004740012   74.7
7  1020480016   64.4
8  3021470021  154.3
9  3021390014   74.0

## Export final data

In [63]:
df.to_csv('../data/clean/ll84_cleaned.csv', index=False)
print(f'Exported {len(df)} rows')

Exported 30135 rows