## 1. Import and Inspect Data

In [15]:
import pandas as pd

# create a datafram from my
df = pd.read_json("../data/raw/ll84_raw.json", orient="records")

print("A look at the raw data...")
df.head()
df.info()
df.describe()

A look at the raw data...
<class 'pandas.DataFrame'>
RangeIndex: 33684 entries, 0 to 33683
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   property_id                33684 non-null  int64
 1   nyc_borough_block_and_lot  33684 non-null  str
 2   borough                    32407 non-null  str
 3   site_eui_kbtu_ft           33684 non-null  str
dtypes: int64(1), str(3)
memory usage: 1.0 MB

        property_id
count  3.368400e+04
mean   1.219369e+07
std    1.012337e+07
min    7.365000e+03
25%    4.406346e+06
50%    6.735348e+06
75%    2.078758e+07
max    3.609357e+07

## 2. Rename Columns

In [11]:
df.columns = df.columns.str.strip().str.lower()

df = df.rename(columns={
    "nyc_borough_block_and_lot": "bbl",
    "property_id": "pid",
    "site_eui_kbtu_ft": "eui"
})

print("Inspect row names")
df.head()
df.info()

Inspect row names
<class 'pandas.DataFrame'>
RangeIndex: 33684 entries, 0 to 33683
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   pid      33684 non-null  int64
 1   bbl      33684 non-null  str
 2   borough  32407 non-null  str
 3   eui      33684 non-null  str
dtypes: int64(1), str(3)
memory usage: 1.0 MB

## 3. Set Data Types

In [12]:
df["bbl"] = pd.to_numeric(df["bbl"], errors="coerce")
df["eui"] = pd.to_numeric(df["eui"], errors="coerce")

print("Inspect new typing: ")
print(df.dtypes)

Inspect new typing:
pid          int64
bbl        float64
borough        str
eui        float64
dtype: object

## 4. Standardize Data Entries

In [13]:
# # clean string data
# df["borough"] = df["borough"].str.strip().str.lower()

# # drop duplicate rows
# df.drop_duplicates(inplace=True)

# # drop entries with critical missing values
# df.dropna(subset=['building_area_sqft', 'electricity_use_kwh'], inplace=True)
# df.dropna(subset=['bbl', 'bin'], how='all', inplace=True) # drop any row with neither bbl nor bin

# # fill remaining entries with missing values
# df['borough'] = df['borough'].fillna('unknown')
# df['bbl'] = df['bbl'].fillna(0)
# df['bin'] = df['bin'].fillna(0)

# # fix data types on newly filled data
# df['bbl'] = df['bbl'].astype(int)
# df['bin'] = df['bin'].astype(int)
# df['building_area_sqft'] = df['building_area_sqft'].astype(int)


# print("test for null and duplicate rows post-cleaning: ")
print(df.isnull().sum())
print(f'Duplicate rows: {df.duplicated().sum()}')

pid            0
bbl        11900
borough     1277
eui         2796
dtype: int64
Duplicate rows: 367

## Final check

In [7]:
print(df.shape)
print(df.isnull().sum())
print(df.dtypes)
df.head(10)

(28391, 6)
pid                    0
bbl                    0
bin                    0
borough                0
electricity_use_kwh    0
building_area_sqft     0
dtype: int64
pid                      int64
bbl                      int64
bin                      int64
borough                    str
electricity_use_kwh    float64
building_area_sqft       int64
dtype: object

,pid,bbl,bin,borough,electricity_use_kwh,building_area_sqft
0,6664906,3052370038,3121216,brooklyn,55685.1,27820
1,6664908,1008190014,1015410,manhattan,518669.0,29532
2,6664909,1010557501,1070034,manhattan,173508.9,30700
3,6664910,1004750056,1007082,manhattan,204243.6,33029
4,6664912,1006980044,1012395,manhattan,79272.3,42800
5,6664913,4019860001,4048852,queens,126669.8,37963
6,6664914,1004740012,1007037,manhattan,701229.7,34886
7,6664916,1020480016,1060906,manhattan,245682.7,52976
8,6664917,3021470021,3059680,brooklyn,116791.9,31394
9,6664918,3021390014,3059628,brooklyn,116934.8,27739

## Export final data

In [8]:
df.to_csv('../data/processed/ll84_cleaned.csv', index=False)
print(f'Exported {len(df)} rows')

Exported 28391 rows